---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="7"
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="debian" tag="bullseye"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: HAjQhtVt3o9kDZdwLC8ZgeZwgf1zCMo7pneWQ08KwC4TfaInoHgzC4TX/GVU3oXagFq2UTukcLYbrUlOHczfuE690CjF20seepsPzu+G4P5k9qmS7cdU2bBwOwXNJhEkY4aablqr3hiR4/0pyWaH9QaNAaUfmvqKnBZ2iKIiQeCa2FNMb1bCvD9O7C9D0aUkhGMy5+2ra4lRdMK5cBzE4GkfEKuwxXH34v3SYNYtypFosBo768eVs+5EQMLNEOwq5fHqa7AvVFeOjKgJxm3cJiOjLaCAGRiMIlwkJnuL4/pdx1MvmYgTorRSB0mASLOi31Kvm+EaTOMXeDYuNMxsC7iCNfnH3w/LqxBSUIluGZQqTm6J4jBa7kMAN8+FEN80/ChOApYhDn7B27o6gkZQvJSWAOSc++7uyWlHd9ybb+7Ljy+R3GMMRubvKFzfhj2ny2Bc7pffokrtvI7JYDkFc3/VGY8b0CHwAt7c1i2rl0HbJ1ul0+dWMoSwVSByY+KhJyROpNDXJp21mgVFo7mlIitlG9Wlbfpw4QE5HMhLsoXpmSjuelLagGsPPg7drFIdYDkqCBLoEYPU5SKIIzKxT8PiU9CXqobR16ii71ydb6Dmu+TIsIKiwGOLLRc8uBzIuXAueiL6EWaIffyl9jIaLQbH5+GoEHKXjTLiK9Yx8mA=
  email: false
