---
roles:
  - name: robertdebock.bootstrap
  - name: robertdebock.mysql
  - name: robertdebock.buildtools
  - name: robertdebock.epel
  - name: robertdebock.python_pip
  - name: robertdebock.postgres
collections:
  - name: community.postgresql
  - name: community.mysql
  - name: community.general
