---
- name: test if backup_directory is set correctly
  assert:
    that:
      - backup_directory is defined
      - backup_directory | length > 0

- name: test if backup_remote_directory is set correctly
  assert:
    that:
      - backup_remote_directory is defined
      - backup_remote_directory | length > 0

- name: test if backup_cleanup is set correctly
  assert:
    that:
      - backup_cleanup is defined
      - backup_cleanup | type_debug == "bool"

- name: test if backup_timestamp is set correctly
  assert:
    that:
      - backup_timestamp is defined
      - backup_timestamp | length > 0

- name: test if backup_format is set correctly
  assert:
    that:
      - backup_format is defined
      - backup_format | length > 0
      - backup_format in ["tgz", "zip", "bz2"]

- name: test if backup_objects is set correctly
  assert:
    that:
      - backup_objects | length > 0
      - backup_objects is iterable
  when:
    - backup_objects is defined

- name: test if item in backup_objects is set correctly
  assert:
    that:
      - item.name is defined
      - item.name | length > 0
      - item.type is defined
      - item.type | length > 0
      - item.type in ["directory", "mysql"]
      - item.source is defined
      - item.source | length > 0
  loop: "{{ backup_objects }}"
  when:
    - backup_objects is defined
