---
# tasks file for backup
- name: create remote_backup_directory
  file:
    path: "{{ backup_remote_directory }}"
    state: directory

- name: create backup_directory
  file:
    path: "{{ backup_directory }}/{{ inventory_hostname }}"
    state: directory
  connection: local
  become: no

- name: loop over objects in backup_objects
  include_tasks: object.yml
  with_items: "{{ backup_objects }}"
  loop_control:
    loop_var: object
  when:
    - backup_objects is defined
