---
- name: archive directory object
  archive:
    path: "{{ object.source }}"
    dest: "{{ backup_remote_directory }}/{{ object.type }}-{{ object.name }}-{{ backup_timestamp }}.{{ object.format | default(backup_format) }}"
    exclude_path: "{{ object.exclude_path | default(omit) }}"
    format: "{{ object.format | default(backup_format) }}"
  when:
    - object.type == "directory"

- name: dump mysql object
  mysql_db:
    name: "{{ object.name }}"
    state: dump
    target: "{{ backup_remote_directory }}/{{ object.type }}-{{ object.name }}-{{ backup_timestamp }}.sql"
  when:
    - object.type == "mysql"

- name: compress mysql object
  archive:
    path: "{{ backup_remote_directory }}/{{ object.type }}-{{ object.name }}-{{ backup_timestamp }}.sql"
    dest: "{{ backup_remote_directory }}/{{ object.type }}-{{ object.name }}-{{ backup_timestamp }}.{{ object.format | default(backup_format) }}"
    format: "{{ object.format | default(backup_format) }}"
  when:
    - object.type == "mysql"

- name: fetch object
  fetch:
    src: "{{ backup_remote_directory }}/{{ object.type }}-{{ object.name }}-{{ backup_timestamp }}.{{ object.format | default(backup_format) }}"
    dest: "{{ backup_directory }}/{{ inventory_hostname }}/"
    flat: yes
  become: no

- name: cleanup object
  file:
    path: "{{ backup_remote_directory }}/{{ object.type }}-{{ object.name }}-{{ backup_timestamp }}.{{ object.format | default(backup_format) }}"
    state: absent
  when:
    - backup_cleanup | bool
