---
- name: archive directory object
  archive:
    path: "{{ object.source }}"
    dest: "{{ backup_remote_directory }}/{{ object.type }}-{{ object.name }}-{{ backup_timestamp }}.tar.gz"
  when:
    - object.type == "directory"

- name: archive mysql object
  mysql_db:
    name: "{{ object.name }}"
    state: dump
    target: "{{ backup_remote_directory }}/{{ object.type }}-{{ object.name }}-{{ backup_timestamp }}.sql.gz"
  when:
    - object.type == "mysql"

- name: fetch object
  fetch:
    dest: "{{ backup_directory }}/"
    src: "{{ backup_remote_directory }}/{{ object.type }}-{{ object.name }}-{{ backup_timestamp }}.tar.gz"
    flat: yes

- name: cleanup object
  file:
    path: "{{ backup_remote_directory }}/{{ object.type }}-{{ object.name }}-{{ backup_timestamp }}.tar.gz"
    state: absent
  when:
    - backup_cleanup
