---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: robertdebock.backup
      backup_cleanup: false
      backup_directory: backups
      backup_remote_directory: /data
      backup_timestamp: "{{ ansible_date_time.date }}"
      backup_format: gz
      backup_objects:
        - name: home
          type: directory
          source: /home
        - name: test_db
          type: mysql
          source: test_db
          format: zip
        - name: test_db
          type: postgres
          source: test_db
