---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-backup
      backup_directory: backups
      backup_remote_directory: /data
      backup_cleanup: yes
      backup_timestamp: "{{ ansible_date_time.date }}"
      backup_format: gz
      backup_objects:
        - name: Home
          type: directory
          source: /home
        - name: Test_db
          type: mysql
          source: test_db
          format: zip
        - name: Test_db
          type: postgres
          source: test_db
